In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

act_30_path = r"D:\projects\adversarial_robustness\experiments\exp1_cmpe597_regular_mnist_robust30\activations.npy"
act_50_path = r"D:\projects\adversarial_robustness\experiments\exp1_cmpe597_regular_mnist_robust50\activations.npy"
act_70_path = r"D:\projects\adversarial_robustness\experiments\exp1_cmpe597_regular_mnist_robust70\activations.npy"

act1 = np.load(act_30_path)
act2 = np.load(act_50_path)
act3 = np.load(act_70_path)

In [47]:
def get_slice(act):
    slice_size = act.shape[-1] // 5
    #act = act[:, :, :, slice_size*2:slice_size*3, slice_size*2:slice_size*3].mean(axis=-1).mean(axis=-1)
    act = np.vstack([act[0], act[1]])
    act = act.reshape((act.shape[0], -1))
    return act
    #return act[:, :, :, 6, 6]

"""def plot_5_dims(act):
    act_slice = get_slice(act)
    
    fig, ax = plt.subplots(2, 5, figsize=(22, 10))
    ax_i = -1
    for i in range(5):
        for j in range(i+1, 5):
            ax_i += 1
            ax_y, ax_x = ax_i // 5, ax_i % 5
            ax[ax_y, ax_x].scatter(x=act_slice[0, :, i], y=act_slice[0, :, j], c="blue")
            ax[ax_y, ax_x].scatter(x=act_slice[1, :, i], y=act_slice[0, :, j], c="red")
            
    plt.legend(["3", "8"])
    plt.show()"""

'def plot_5_dims(act):\n    act_slice = get_slice(act)\n    \n    fig, ax = plt.subplots(2, 5, figsize=(22, 10))\n    ax_i = -1\n    for i in range(5):\n        for j in range(i+1, 5):\n            ax_i += 1\n            ax_y, ax_x = ax_i // 5, ax_i % 5\n            ax[ax_y, ax_x].scatter(x=act_slice[0, :, i], y=act_slice[0, :, j], c="blue")\n            ax[ax_y, ax_x].scatter(x=act_slice[1, :, i], y=act_slice[0, :, j], c="red")\n            \n    plt.legend(["3", "8"])\n    plt.show()'

In [60]:
from sklearn.decomposition import PCA

act = act1
act_slice = get_slice(act)
pca = PCA(n_components=5)
pca.fit(act_slice[:500])
print(pca.explained_variance_ratio_)

pca = PCA(n_components=5)
pca.fit(act_slice[500:])
print(pca.explained_variance_ratio_)

[0.11785731 0.09575818 0.06738835 0.05396928 0.04660016]
[0.12134703 0.08214576 0.05687864 0.052313   0.047494  ]


In [61]:
from sklearn.decomposition import PCA

act = act2
act_slice = get_slice(act)
pca = PCA(n_components=5)
pca.fit(act_slice[:500])
print(pca.explained_variance_ratio_)

pca = PCA(n_components=5)
pca.fit(act_slice[500:])
print(pca.explained_variance_ratio_)

[0.1242554  0.10513357 0.06748427 0.05618605 0.05052777]
[0.12140512 0.08909638 0.06049634 0.04820549 0.04382665]


In [62]:
from sklearn.decomposition import PCA

act = act3
act_slice = get_slice(act)
pca = PCA(n_components=5)
pca.fit(act_slice[:500])
print(pca.explained_variance_ratio_)

pca = PCA(n_components=5)
pca.fit(act_slice[500:])
print(pca.explained_variance_ratio_)

[0.12616943 0.09718695 0.07018437 0.0554196  0.05238372]
[0.11241765 0.08648881 0.05952363 0.04912027 0.04240352]
